//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAFE_Song_Lo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billinfo_audit
    {
        public int id { get; set; }
        public Nullable<int> idbill { get; set; }
        public Nullable<int> idfood { get; set; }
        public Nullable<int> cout { get; set; }
    }
}
