//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAFE_Song_Lo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhapsanpham
    {
        public int idsanpham { get; set; }
        public Nullable<int> idncc { get; set; }
        public string tensanpham { get; set; }
        public Nullable<double> tongtien { get; set; }
    
        public virtual nhacungcap nhacungcap { get; set; }
    }
}
