//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAFE_Song_Lo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_audit
    {
        public int id { get; set; }
        public int idstaff { get; set; }
        public string name { get; set; }
        public System.DateTime changedate { get; set; }
        public string action { get; set; }
    }
}
